# Generated by Django 4.2.5 on 2023-09-22 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_temporal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='producto_temporal',
        ),
    ]
