# Generated by Django 4.2.5 on 2023-09-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_delete_producto_temporal'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto_temporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_compra', models.CharField(max_length=15)),
                ('productos', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
